swagger: '2.0'
info:
  description: >-
    Api definition for prime services, which will support soperations of prime an investments app.
  version: 1.0.0
  title: Prime-Services
  termsOfService: 'https://github.com/Dhruvaraju/prime-services/blob/main/LICENSE'
  contact:
    email: test@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: NOT-DEPLOYED-YET
basePath: /v2
tags:
  - name: login
    description: User access management
  - name: ipo
    description: To support IPO
  - name: buy-and-sell
    description: Stocks sale and buy
  - name: financial-product-shop
    description: Income and Wealth-management portal
schemes:
  - http
paths:
  /register:
    post:
      tags:
        - login
      summary: Create user
      description: Initial registration for user authentication
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
  /user/login:
    post:
      tags:
        - login
      summary: Logs user into the system
      description: 'Used to authenticate user with system'
      operationId: loginUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: The user name for login
          required: true
          schema:
            $ref: '#/definitions/User-cred'
      responses:
        '200':
          description: successful operation
          schema:
             $ref: '#/definitions/Login-response'
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: Invalid username/password supplied
  /ipo/register:
    post:
      tags:
        - ipo
      summary: To register user for an ipo
      description: 'Register user for an ipo'
      operationId: registerIPO
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Initial registration for user for an ipo, ipo quote information will not be provided while making this call
          required: true
          schema:
            $ref: '#/definitions/Ipo-details'
      responses:
        '200':
          description: Register for Ipo successfully
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
        '403':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
        '500':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
    put:
      tags:
        - ipo
      summary: Updating IPO quote details
      description: 'Updating IPO quote details'
      operationId: ipoQuote
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: The register object will be updated with a quote details
          required: true
          schema:
            $ref: '#/definitions/Ipo-details'
      responses:
        '200':
          description: Updated quote details
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
        '403':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
        '500':
          description: Contact an employee for initiating an ipo or call 1800XXXXXX.
  /fpshop/buy:
    post:
      tags:
        - financial-product-shop
      summary: To buy a financial product
      description: 'buy a financial product'
      operationId: fp-buy
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Initial registration for user for an ipo, ipo quote information will not be provided while making this call
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      responses:
        '200':
          description: Product added to your portfolio
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: System unavailable try later.
        '403':
          description: System unavailable try later.
        '500':
          description: System unavailable try later.
  /fpshop/catalog:
    get:
      tags:
        - financial-product-shop
      summary: To get list of all financial products
      description: 'List of financial products'
      operationId: fp-buy
      produces:
        - application/json
      responses:
        '200':
          description: List of all financial products
          schema:
            type: "array"
            $ref: '#/definitions/Financial-product'
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: System unavailable try later.
        '403':
          description: System unavailable try later.
        '500':
          description: System unavailable try later.
  /bns/buy:
    post:
      tags:
        - buy-and-sell
      summary: To buy a stock
      description: 'buy a stock'
      operationId: buy
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: buying a stock
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      responses:
        '200':
          description: Product added to your portfolio
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: System unavailable try later.
        '403':
          description: System unavailable try later.
        '500':
          description: System unavailable try later.
  /bns/sell:
    post:
      tags:
        - buy-and-sell
      summary: To sell a stock
      description: 'sell a stock'
      operationId: sell
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: buying a stock
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      responses:
        '200':
          description: Product sale initiated successfully
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: System unavailable try later.
        '403':
          description: System unavailable try later.
        '500':
          description: System unavailable try later.
definitions:
  Financial-product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      productId:
        type: integer
        format: int64
      productDescription:
        type: string
      typeOfProduct:
        type: string
        enum:
          - INCOME
          - WEALTH-MANAGEMENT
      paymentType:
        type: string
        enum:
          - Monthly
          - Quarterly
          - Yearly
      minimumPaymentAmount:
        type: number
        format: double
        default: 10000
    xml:
      name: Order
  Ipo-details:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userName:
        type: string
        example: norad01
      companyName:
        type: string
        example: DC Comics INC
      currentMarketCap:
        type: integer
        format: int64
        example: 500000
      openForSale:
        type: integer
        format: int64
        example: 25
        description: maximum of 49%
      ipoQuote:
        $ref: '#/definitions/IpoQuoteDetails'
  IpoQuoteDetails:
    type: object
    properties:
      description:
        type: string
        description: explanation about a company and its performance recently
      issueDate:
        type: string
        format: date
        example: "2021-05-15"
        description: date format should be YYYY-MM-DD
      issueSize:
        type: integer
        format: int64
        example: 300000
      issuePrice:
        type: integer
        format: int64
        example: 2
      lotSize:
        type: integer
        format: int64
        example: 200
      closingDate:
        type: string
        format: date
        example: "2021-10-12"
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      organization-name:
        type: string
        example: DC comics
        description: Mandatory when user-type is organization
      panNumber:
        type: string
      password:
        type: string
      addressLine-01:
        type: string
      addressLine-02:
        type: string
        description: Optional Field
      state:
        type: string
      country:
        type: string
      pinCode:
        type: integer
        format: int64
      userType:
        type: string
        enum:
        - INDIVIDUAL
        - ORGANIZATION
  User-cred:
    type: object
    required:
      - userName
      - password
    properties:
      userName:
        type: string
        example: norad01
      password:
        type: string
        example: secure-ops
  Login-response:
    type: object
    required:
    - message
    properties:
      message:
        type: boolean
        example: true / false
  TransactionRequest:
    type: object
    required:
      - userName
      - type
      - quantity
    properties:
      userName:
        type: string
        example: norad01
      type:
        type: string
        enum:
          - Buy
          - Sell
      quantity:
        type: number
        format: int64
      orderType:
        type: string
        enum:
          - Market
          - Limit
      priceLimit:
        type: number
        format: double
        description: mandatory when order type is limit
      marketPrice:
        type: number
        format: double
  Error:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
        enum:
          - 400
          - 401
          - 403
          - 404
          - 500
          - 301
          - 302
          - 303
          - 304
      description:
        type: string
